- hosts: 172.17.0.3
  tasks:
    - maven_artifact:
        group_id: com.maven.demo
        artifact_id: jenkins
        repository_url: 'http://host.docker.internal:8110/repository/nexusdeploymentrepo/'
        username: admin
        password: 123456
        dest: /download
